### PR TITLE
fix!: Add field-length indicator to BFE encoding of polynomial

### LINKED ISSUE #203: Manual `BfieldCodec` implementation for `Polynomial` is not consistent with a derived one
In #200 we manually made a `BFieldCodec` implementation for `Polynomial`. But this implementation is inconsistent with a derived one that would have a size indicator for the coefficients field. This creates problems downstream, and especially the [`tasm-lang`](https://github.com/TritonVM/tasm-lang) would have to special-case a lot on `Polynomial` and basically make it into an atomic/native type for this to work.
```rust
pub struct Polynomial<FF: FiniteField> {
    pub coefficients: Vec<FF>,
}
```

The solution is to keep the manual implementation (because we need to remove trailing zeros from the encoding to easily read the degree of an encoded polynomial in Triton VM) but change it such that it carries the length of the field.

### PR DESCRIPTION
**Pull request by Sword-Smith**
This field-length value is needed in the encoding to allow downstream dependencies to treat an encoded polynomial stored in Triton VM RAM as any other struct, since all encoded struct are assumed to be encoded consistently with a derived `BFieldCodec` implementation.

This closes #203.

### CODE REVIEW

File: twenty-first/src/math/bfield_codec.rs [hunk 1]
```diff
@@ -373,14 +375,32 @@ pub enum PolynomialBFieldCodecError {
...
+        if sequence.is_empty() {
+            return Err(Self::Error::Other(BFieldCodecError::EmptySequence));
+        }
+
+        let coefficients_field_length_indicator: Result<usize, _> = sequence[0].value().try_into();
+        let Ok(coefficients_field_length_indicator) = coefficients_field_length_indicator else {
+            return Err(Self::Error::Other(BFieldCodecError::InvalidLengthIndicator));
+        };
+
+        let indicated_sequence_length = coefficients_field_length_indicator + 1;
```
Comment (jan-ferdinand) [inline twenty-first/src/math/bfield_codec.rs:394]: I'm not sure what the `+ 1` is for. Add a comment?

File: twenty-first/src/math/bfield_codec.rs [hunk 2]
```diff
@@ -373,14 +375,32 @@ pub enum PolynomialBFieldCodecError {
...
+        if sequence.len() < indicated_sequence_length {
+            return Err(Self::Error::Other(BFieldCodecError::SequenceTooShort));
+        }
+
+        if sequence.len() > indicated_sequence_length {
+            return Err(Self::Error::Other(BFieldCodecError::SequenceTooLong));
+        }
+
+        let decoded_vec = Vec::<T>::decode(&sequence[1..])?;
```
Comment (jan-ferdinand) [inline twenty-first/src/math/bfield_codec.rs:403]: Possibly:
```suggestion
        let decoded_vec = match sequence.len().cmp(&indicated_sequence_length) {
            Ordering::Equal => Vec::<T>::decode(&sequence[1..]),
            Ordering::Less => Err(BFieldCodecError::SequenceTooShort),
            Ordering::Greater => Err(BFieldCodecError::SequenceTooLong),
        }?;
```

File: twenty-first/src/math/bfield_codec.rs [hunk 3]
```diff
@@ -732,58 +762,60 @@ mod tests {
...
-    #[proptest]
-    fn disallow_trailing_zeros_in_poly_encoding_bfe(
-        mut polynomial: Polynomial<BFieldElement>,
-        #[filter(!#leading_coefficient.is_zero())] leading_coefficient: BFieldElement,
-        #[strategy(1usize..30)] num_leading_zeros: usize,
+    fn disallow_trailing_zeros_in_poly_encoding_prop<T: FiniteField + BFieldCodec>(
+        mut polynomial: Polynomial<T>,
+        leading_coefficient: T,
+        num_leading_zeros: usize,
     ) {
```
Comment (jan-ferdinand) [inline twenty-first/src/math/bfield_codec.rs:769]: I like this. If you make the return type a `PropTestResult`, you can even keep using `prop_assert_eq!` and `prop_assert!`.
```suggestion
    fn disallow_trailing_zeros_in_poly_encoding_prop<T: FiniteField + BFieldCodec>(
        mut polynomial: Polynomial<T>,
        leading_coefficient: T,
        num_leading_zeros: usize,
    ) -> TestCaseResult {
```

It would also require
- returning `Ok(())` in this function, and
- changing the two `proptest`s that use this function to conclude with `?;`.

**Review by jan-ferdinand — APPROVED** [review]
Good stuff. I left some suggestions in-line.

File: twenty-first/src/math/bfield_codec.rs (hunk 2 above)
Comment (Sword-Smith) [reply twenty-first/src/math/bfield_codec.rs:403]: Why not?

File: twenty-first/src/math/bfield_codec.rs (hunk 3 above)
Comment (Sword-Smith) [reply twenty-first/src/math/bfield_codec.rs:769]: Done
